# Generated by Django 3.1.7 on 2021-03-20 18:45

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_prod',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
