# Generated by Django 3.1.7 on 2021-03-20 19:01

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_photo_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
